markdown: kramdown
markdown_ext: markdown,mkd,mkdn,md
highlighter: rouge
permalink: /:year/:month/:title/
safe: false
exclude: ['README.md', 'tmp/', 'Gemfile', 'Gemfile.lock']
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-assets
  - jekyll-extlinks

excerpt_separator: <!--more-->

assets:
  sources:
    - "_assets/css"
    - "_assets/js"

extlinks:
  attributes: {target: _blank, class: 'external'}
  rel_exclude: ['engineering.trio.dev']