version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: .circleci/deploy-github.sh
workflows:
  version: 2
  build:
    jobs:
      deploy:
        branches:
          only:
            - master